---
label: Product
hide_body: false
fields:
- type: text
  name: id
  label: ID
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price
  label: Price
- type: number
  name: order
  label: Order
  description: numerical order of sorting products
- type: file
  name: default_thumbnail_image
  label: Default Thumbnail Image
- type: file
  name: default_original_image
  label: Default Original Image
- type: select
  name: category
  label: Category
  config:
    source:
      type: pages
      section: category
- type: select
  name: section
  label: Section
  config:
    source:
      type: custom
    options:
    - Store
    - About
    - Home
- type: boolean
  name: featured
  label: Featured
  default: false
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- content/products/plant1.md
- content/products/plant2.md
- content/products/plant3.md
- content/products/plant4.md
- content/products/plant5.md
- content/products/plant6.md
- content/products/plant7.md
- content/products/plant8.md
- content/products/plant9.md
